#!/bin/bash

#cd /path/to/png/storage/2010/01/c/

#mkdir optimized
## store optimized images in optimized directory ##
## Keep file system permission and make a backup of original PNG (see options below)  ##
#for i in *.png; do optipng -o5 -quiet -keep -preserve -dir optimized -log optipng.log "$i"; done
 
for i in *.png; do cp $i.{png,png.orig}; optipng -o5 -quiet -keep -preserve -log optipng.log "$i"; done
